run:
  seed_val: 1409
  msoa_lim: 2
store:
  dat:
    raw:
      base_dir: Data/Raw
      dir_names:
        shapefiles: Shapefiles
      shapefile_layer_names:
        ew_msoa: Middle_Layer_Super_Output_Areas_(December_2011)_Boundaries
        uk_full: gadm36_GBR_0
    wrangled:
      base_dir: Data/Processed
      dir_names:
        shapefiles: Shapefiles
      file_names:
        shapefiles:
          ew_msoa: ew_msoa.rds
          ew_msoa_region: ew_msoa_region.rds
          uk_full: uk_full.rds
      file_names_ref:
        shapefiles:
          msoa: shapefiles.RData
  out:
    base_dir: Output
