run:
  seed_val: 1409
  msoa_lim: 2
store:
  save:
    imputed_tus_dat: 'false'
  dat:
    raw:
      dirs:
        base: Data/Raw
        shapefiles: Shapefiles
        population: Population
        tus: TimeUseSurvey
        misc: Misc
      shapefile_layers:
        ew_msoa: Middle_Layer_Super_Output_Areas_(December_2011)_Boundaries
        uk_full: gadm36_GBR_0
      tus:
        uk_metadata_location: uktus_metadata_location.csv
      misc:
        nssec_class: nssec_classification.csv
        soc2010_class: soc2010_classification.csv
        sic2007_class: sic2007_classification.csv
      nm_patterns:
        pop_lad_tus: lad_TUS_
    interim:
      dirs:
        base: Data/Interim
      fnames:
        imputed_tus_dat: imputed_tus_dat.rds
    wrangled:
      dirs:
        base: Data/Processed
        shapefiles: Shapefiles
        population: Population
        tus: TimeUseSurvey
      shapefiles:
        ew_msoa: ew_msoa.rds
        ew_msoa_region: ew_msoa_region.rds
        uk_full: uk_full.rds
      shapefiles_ref:
        msoa: shapefiles.RData
      population:
        pop_dat: pop_dat.rds
      population_ref:
        pop_dat: pop_dat.RData
      time_use_survey:
        tus_dat: tus_dat.rds
      time_use_survey_ref:
        tus_dat: tus_dat.RData
  out:
    dirs:
      base: Output
      activities: CaseStudy2/Activities
    nm_patterns:
      activities: activities_
