# SPDX-FileCopyrightText: [2024] University of Manchester
# SPDX-License-Identifier: apache-2.0

# To deal with 'no visible binding for global variable' on R CMD CHECK

utils::globalVariables(c(

  # ".",
  ":=",

  # get_merge_locn
  "max_propn",
  "first_locn",

  # impute_tus_dat
  "most_popular_locn",

  # calculate_household
  "pop_id",
  "housetype",
  "uniid",

  # collate_results_jul_2021
  "pop_dat",
  "micro_group",
  "pm25_aurn_near",
  "pm25_aurn_near_inh",
  "pm25_aurn_near_tns",
  "pm25_aurn_near_hhd",
  "pm25_ltn_near",
  "pm25_ltn_near_inh",
  "pm25_ltn_near_tns",
  "pm25_ltn_near_hhd",
  "pm25_gm_near",
  "pm25_gm_near_inh",
  "pm25_gm_near_tns",
  "pm25_gm_near_hhd",
  "exposure_aurn",
  "exposure_ltn",
  "exposure_gm",

  # collate_results_q1_2021
  "micro_group",
  "pm25_cams_agg",
  "pm25_cams_agg_inh",
  "pm25_cams_agg_tns",
  "pm25_cams_agg_hhd",
  "pm25_emep_agg",
  "pm25_emep_agg_inh",
  "pm25_emep_agg_tns",
  "pm25_emep_agg_hhd",
  "pm25_five",
  "pm25_five_inh",
  "pm25_five_tns",
  "pm25_five_hhd",
  "exposure_cams",
  "exposure_emep",
  "exposure_five",

  # plot_results_jul_2021
  "parent_area_name",
  "area_name",
  "exposure_gm",
  "pm25_gm_near",
  "sex_label",
  "agegr4_label",
  "outdoor",
  "lower",
  "upper",
  "pred",
  "variable",
  "value",

  # plot_results_q1_2021
  "parent_area_name",
  "area_name",
  "exposure_emep",
  "pm25_emep_agg",
  "sex_label",
  "agegr4_label",
  "outdoor",
  "lower",
  "upper",
  "pred",
  "variable",
  "value",
  "exposure_five",

  # process_activities
  "location",
  "n",
  "p",
  "tmp",
  "location_popular",
  "location_label",
  "area_id",
  "percmissing",
  "hour",
  "day",
  "day_label",
  "daytype",
  "daytype_label",
  "season",
  "season_label",
  "pop_id",
  "minutes",

  # process_exposures_jul_2021
  "pop_id",
  "area_id",
  "sex",
  "sex_label",
  "agegr4",
  "agegr4_label",
  "nssec5",
  "nssec5_label",
  "hour",
  "pm25_aurn_near",
  "pm25_gm_near",
  "pm25_ltn_near",

  # process_exposures_q1_2021
  "area_id",
  "hour",
  "pm25_cams_agg",
  "pm25_emep_agg",
  "pop_id",
  "sex",
  "sex_label",
  "agegr4",
  "agegr4_label",
  "nssec5",
  "nssec5_label",
  "pm25_five",

  # run_data_prep_pm25_cams
  "parent_area_name",
  "value",
  "layer",
  "pm25",
  "weight",
  "area_id",
  "hour",
  "pm25_cams_cent",
  "pm25_cams_agg",

  # run_data_prep_pm25_emep
  "parent_area_name",
  "value",
  "layer",
  "pm25",
  "weight",
  "area_id",
  "hour",
  "pm25_cams_cent",
  "pm25_cams_agg",

  # run_data_prep_pm25_gm
  "parent_area_name",
  "site",
  "code",
  "longitude",
  "latitude",
  "PM2.5",
  "hour",
  "ds",
  "pm2.5",
  "variable",
  "start_date",
  "end_date",
  "ws",
  "wd",
  "air_temp",
  "area_id",
  "pm25_aurn",
  "code_aurn",
  "pm25_ltn",
  "code_ltn",
  "code_gm",
  "pm25_aurn_near",
  "code_aurn_near",
  "pm25_ltn_near",
  "code_ltn_near",
  "pm25_gm_near",
  "code_gm_near",

  # run_data_prep_population
  "Sex",
  "age",
  "agegr1_label",
  "agegr2_label",
  "agegr3_label",
  "agegr4_label",
  "sic2d07",
  "soc2010",
  "nssec5",
  "nssec5_label",
  "hhnssec5",
  "hhnssec5_label",
  "soc2010_label",
  "sic1_label",
  "sic2_label",
  "pop_id",
  "pid_tus",
  "hid",
  "housetype",
  "area",
  "agegr1",
  "agegr2",
  "agegr3",
  "agegr4",
  "sex",
  "sex_label",
  "pwkstat",
  "pwkstat_label",
  "work",
  "sic2",
  "sic1",
  "punknown",
  "pmunknown",
  "keyworkercasa",
  "keyworkeroccupationgroupcasa",

  # run_data_prep_study_region
  "X",
  "Y",
  "msoa11cd",
  "msoa11nm",
  "long",
  "lat",
  "area_name",
  "parent_area_name",

  # run_data_prep_tus
  "psu",
  "serial",
  "pnum",
  "DVAge",
  "agegr1_label",
  "agegr2_label",
  "agegr3_label",
  "agegr4_label",
  "pid_tus",
  "agegr1",
  "agegr2",
  "agegr3",
  "agegr4",
  "sex",
  "sex_label",
  "pwkstat",
  "pwkstat_label",
  "SIC2007",
  "dsic",
  "nssec",
  "XSOC2010",
  "dsoc",
  "soc2010",
  "soc2010_label",
  "soc2010group",
  "nssec_label",
  "nssec5",
  "nssec5_label",
  "sic1",
  "sic1_label",
  "sic2_label",
  "age",
  "soc2010group_label",
  "sic2",
  "sicgroup",
  "sicgroup_label",
  "DiaryDay_Act",
  "act_id",
  "DiaryDate_Act",
  "day",
  "day_label",
  "daytype",
  "daytype_label",
  "season",
  "season_label",
  "dia_wt_a",
  "dia_wt_b",
  "act1_1",
  "act1_144",
  "wher_1",
  "wher_144",
  "location",

  # sample_population
  "n",
  "strata",
  "sums",
  "pop_id",
  "sex",
  "agegr4",
  "nssec5"
))
